[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=4
    -DBOARD_HAS_PSRAM=0
    -I shared
build_unflags = -std=gnu++11
